### ISSUE TITLE
Enemy: Bulborb

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#12]
## Tasks to Complete

- [*] Model this enemy
- [ ] Rig for animation
- [ ] Texture this enemy
- [ ] Complete all animations
- [ ] Import into game engine and write appropriate AI and Behaviors

## Animations

- [ ] Sleeping
- [ ] Woken Up / Startled
- [ ] Turn in Place
- [ ] Shake off Pikmin
- [ ] Chomp-o
- [ ] Fall Forward (Chomp failed)
- [ ] Toss and Chew (Chomp succeeded)
- [ ] Walk Forwards
- [ ] Fall Asleep
- [ ] Death
- [ ] Lost Target (Look Around)
