### ISSUE TITLE
Enemy: Dwarf Bulborb

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#13]
## Tasks to Complete

- [x] Model this enemy
- [ ] Rig for animation
- [ ] Texture this enemy
- [ ] Complete all animations
- [ ] Import into game engine and write appropriate AI and Behaviors

## Animations

- [ ] Idle (Sniffing Ground)
- [ ] Alerted
- [ ] Turn Left / Turn Right
- [ ] Shake off Pikmin
- [ ] Chomp-o
- [ ] Walk Forwards
- [ ] Squished
- [ ] Death
