### ISSUE TITLE
Enemy: Fiery Blowhog

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#14]
## Tasks to Complete

- [ ] Model this enemy
- [ ] Rig for animation
- [ ] Texture this enemy
- [ ] Complete all animations
- [ ] Import into game engine and write appropriate AI and Behaviors

## Animations

- [ ] Idle, Look Around
- [ ] Walk Forward
- [ ] Turn Left / Right
- [ ] Throw Pikmin Forward
- [ ] Blow Fire
- [ ] Death
