### ISSUE TITLE
Object: Ship

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#15]
## Tasks to Complete

- [x] Model this Object
- [ ] Rig for animation
- [ ] Texture this Object
- [ ] Complete all animations
- [ ] Import into game engine and write appropriate AI and Behaviors

## Animations

- [ ] Idle
- [ ] Accept Treasure
- [ ] Land / Eject Captain
- [ ] Blast Off
