### ISSUE TITLE
Enemy: Snagret

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#16]
A fearsome half-bird, half-snake creature. Towers over Olimar and the Pikmin, and is quite formidable. Taking one down without losing a single Pikmin is a challenging, but not impossible task.

## Tasks to Complete

- [x] Model this enemy
- [ ] Rig for animation
- [ ] Texture this enemy
- [ ] Complete all animations
- [ ] Import into game engine and write appropriate AI and Behaviors

## Animations

- [ ] Emerge (Quick)
- [ ] Emerge (Longer)
- [ ] Idle
- [ ] Pecking (x3)
- [ ] Swallow
- [ ] Shake Off
- [ ] Burrow
- [ ] Death
