### ISSUE TITLE
Enemy: Creeping Crysanthemum

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#17]
This large creature hides underground, exposing only its eyes above ground, which are disguised as harmless flowers. On approach, it pops out of the ground, scattering any nearby Pikmin / players, then proceeds to attack. It has a generous amount of health, and poses a sizable danger to unprepared players.

## Tasks to Complete

- [ ] Model this enemy
- [ ] Rig for animation
- [ ] Texture this enemy
- [ ] Complete all animations
- [ ] Import into game engine and write appropriate AI and Behaviors

## Animations

- [ ] Idle (Flower)
- [ ] Emerge
- [ ] Turn Left / Right
- [ ] Walk Forwards
- [ ] Windup Attack
- [ ] Chomp Pikmin (Attack successful)
- [ ] Knocked Down (Attack failed)
- [ ] Shake Off
- [ ] Burrowing
- [ ] Death
