### ISSUE TITLE
Enemy: Sheargrub (Male and Female)

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#18]
These weaker enemies burrow underground, and usually pop up in swarms of 3-6 when captains / pikmin are nearby. The female variety have no pincers, and are therefore harmless.

## Tasks to Complete

- [ ] Model this enemy
- [ ] Rig for animation
- [ ] Texture this enemy
- [ ] Complete all animations
- [ ] Import into game engine and write appropriate AI and Behaviors

## Animations

- [ ] Burrowed
- [ ] Emerging
- [ ] Walk Forward
- [ ] Attacking (Males Only)
- [ ] Death
