### ISSUE TITLE
Reduce MultipassEngine to MultipassRenderer

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#26]
The Multipass portion of our codebase is just a tad too big and responsible. It should be lightened somewhat, in particular I'd like to see drawable "entities", the camera, and several other "game" type things moved away from it. It should be in charge of running the render and little else.

## Tasks

- [x] Reduce the Camera logic considerably, move Pikmin-specific behavior to an AI
- [x] Refactor DrawableEntity into Drawable, and remove dependency on physics bodies / world
- [ ] Remove the Input subsystem from MultipassEngine and move it to its own module
